*** Reading local file: /opt/airflow/logs/dag_id=dag_con_conexion_postgres/run_id=manual__2022-09-04T20:01:37.601817+00:00/task_id=insertar_en_tabla/attempt=1.log
[2022-09-04, 20:01:39 UTC] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_con_conexion_postgres.insertar_en_tabla manual__2022-09-04T20:01:37.601817+00:00 [queued]>
[2022-09-04, 20:01:39 UTC] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_con_conexion_postgres.insertar_en_tabla manual__2022-09-04T20:01:37.601817+00:00 [queued]>
[2022-09-04, 20:01:39 UTC] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-09-04, 20:01:39 UTC] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-09-04, 20:01:39 UTC] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-09-04, 20:01:39 UTC] {taskinstance.py:1397} INFO - Executing <Task(PostgresOperator): insertar_en_tabla> on 2022-09-04 20:01:37.601817+00:00
[2022-09-04, 20:01:39 UTC] {standard_task_runner.py:52} INFO - Started process 1636 to run task
[2022-09-04, 20:01:39 UTC] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_con_conexion_postgres', 'insertar_en_tabla', 'manual__2022-09-04T20:01:37.601817+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/dag_postgres_database.py', '--cfg-path', '/tmp/tmpukbt6rtz', '--error-file', '/tmp/tmpd8yg252j']
[2022-09-04, 20:01:39 UTC] {standard_task_runner.py:80} INFO - Job 36: Subtask insertar_en_tabla
[2022-09-04, 20:01:40 UTC] {task_command.py:371} INFO - Running <TaskInstance: dag_con_conexion_postgres.insertar_en_tabla manual__2022-09-04T20:01:37.601817+00:00 [running]> on host 6076183c9d93
[2022-09-04, 20:01:40 UTC] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=DavidBU
AIRFLOW_CTX_DAG_ID=dag_con_conexion_postgres
AIRFLOW_CTX_TASK_ID=insertar_en_tabla
AIRFLOW_CTX_EXECUTION_DATE=2022-09-04T20:01:37.601817+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-04T20:01:37.601817+00:00
[2022-09-04, 20:01:40 UTC] {base.py:68} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-09-04, 20:01:40 UTC] {dbapi.py:231} INFO - Running statement: 
            insert into fin_mundo (dt,pais) values ('12-12-2025','Colombia');
            insert into fin_mundo (dt,pais) values ('15-08-2035','Brasil');
            insert into fin_mundo (dt,pais) values ('21-09-2030','Argentina');
            insert into fin_mundo (dt,pais) values ('13-07-2045','Chile');
            insert into fin_mundo (dt,pais) values ('17-11-2028','Ecuador');
            insert into fin_mundo (dt,pais) values ('19-03-2032','Peru');
            insert into fin_mundo (dt,pais) values ('18-08-2026','Uruguay');
            insert into fin_mundo (dt,pais) values ('22-05-2037','Paraguay');
            insert into fin_mundo (dt,pais) values ('12-12-2080','Venezuela');
            insert into fin_mundo (dt,pais) values ('12-12-2071','Mexico');
        , parameters: None
[2022-09-04, 20:01:40 UTC] {dbapi.py:239} INFO - Rows affected: 1
[2022-09-04, 20:01:40 UTC] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=dag_con_conexion_postgres, task_id=insertar_en_tabla, execution_date=20220904T200137, start_date=20220904T200139, end_date=20220904T200140
[2022-09-04, 20:01:40 UTC] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-04, 20:01:40 UTC] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
